server:
  port: 8080

logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:mysql://localhost:3636/hire-me
    username: root
    password: example
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: false
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

app:
  base-url: http://localhost:8080