version: "3"

services:
  mysql:
    image: mysql:8.4
    ports:
      - "3636:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: hire-me
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
